---
- name: "Change storage path"
  set_fact:
    storage: /media/hdd

- name: Ensure the HDD mountpoint exists
  file:
    path: "{{ storage }}"
    state: directory
    mode: 0755

- name: Copy mount units to systemd folder
  template:
    src: media-hdd.mount.j2
    dest: /etc/systemd/system/media-hdd.mount
    owner: root
    group: root
    mode: 0644

- name: Enable mount point
  systemd:
    name: media-hdd.mount
    state: started
    enabled: yes
    daemon_reload: yes
