---
- name: Stat on srv directory
  stat: path=/srv/
  register: srv_dir

- name: Remove /srv/ directory to link it to external HDD
  file: path=/srv/ state=absent
  when: srv_dir.stat.islnk is not defined

- name: Symlink /srv/ to external HDD
  file: src=/media/hdd/ dest=/srv/ state=link
  when: srv_dir.stat.islnk is not defined
