syncthing_web_ui: 0.0.0.0:8384
kawax_id: EHQO24A-A2JOFKB-J2H2WRW-4VUWFHZ-JJDRQP7-MHWDCRO-EMPKTXX-REUTHAX

syncthing_config:
 - { id: eagml-hd53c, label: "Omeka packages", path: /media/hdd/omeka }
 - { id: qaxgo-dqxnt, label: "Kiwix zim files", path: /media/hdd/zim }
 - { id: pjg29-tncz9, label: "Static-site", path: /media/hdd/static-sites }
 - { id: shiqa-hr5j5, label: "Kolibri", path: /media/hdd/kolibri }
 - { id: n97vs-nyscj, label: "Hugo - Mediacenter", path: /media/hdd/hugo }
 - { id: mpmcs-mwruq, label: "OpenStreetMap", path: /media/hdd/osm }

syncthing_master_id_device: 
  - { key: "7FSJQA4-K7VAENU-GRIVR4O-UBNEHHP-SNQYOR4-AZTZBHE-K5B2UQD-D4EBGAW", label: "Bubble", ip_address: 37.187.117.222, port: 22000 }